export const SIGN_IN_AND_SET_JWT = "SIGN_IN_AND_SET_JWT";
export const SIGN_IN_AND_SET_JWT_SUCCESS = "SIGN_IN_AND_SET_JWT_SUCCESS";

export const SIGN_OUT_AND_REMOVE_JWT = "SIGN_OUT_AND_REMOVE_JWT";
export const SIGN_OUT_AND_REMOVE_JWT_SUCCESS =
  "SIGN_OUT_AND_REMOVE_JWT_SUCCESS";

export const JWT_VALIDATE = "JWT_VALIDATE";
export const JWT_VALIDATE_TURE = "JWT_VALIDATE_TURE";
export const JWT_REFRESH = "JWT_REFRESH";
