export const SIGN_IN_AND_SET_JWT = "SIGN_IN_AND_SET_JWT";
export const SIGN_IN_AND_SET_JWT_SUCCESS = "SIGN_IN_AND_SET_JWT_SUCCESS";

export const SIGN_OUT_AND_REMOVE_JWT = "SIGN_OUT_AND_REMOVE_JWT";
export const SIGN_OUT_AND_REMOVE_JWT_SUCCESS =
  "SIGN_OUT_AND_REMOVE_JWT_SUCCESS";

export const VALIDATE_JWT = "VALIDATE_JWT";
export const VALIDATE_JWT_TURE = "VALIDATE_JWT_TURE";
export const REFRESH_JWT = "REFRESH_JWT";
