export const SET_USER_INFORMATION_AND_JWT = "SET_USER_INFORMATION_AND_JWT";
export const SET_USER_INFORMATION = "SET_USER_INFORMATION";

export const REMOVE_UESR_INFORMATION_AND_JWT =
  "REMOVE_UESR_INFORMATION_AND_JWT";
export const REMOVE_UESR_INFORMATION = "REMOVE_UESR_INFORMATION";

export const VALIDATE_JWT = "VALIDATE_JWT";
export const VALIDATE_JWT_TURE = "VALIDATE_JWT_TURE";
export const REFRESH_JWT = "REFRESH_JWT";
